version: '3.9'
services:
  chatglm:
    build: .
    image: chatglm3:torch-1.13.1 
    container_name: chatglm3
    ports:
      - "8000:8000"
      - "7860:7860"
      - "8501:8501"
    volumes:
      - ./models/THUDM:/app/THUDM:cached
    environment:
      - CLI_ARGS=$CLI_ARGS
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
